### ISSUE TITLE
users who are stupid and switch on 'open voting' too early have no way to revert

### ISSUE THREAD

**Issue by antlerboy-benjamintaylor** [heathd/twentyfiveten#1]
it would be very helpful in a future iteration to have the option to switch back (if only before any votes are cast)

**Comment by heathd** [comment]
Ok this should be fixed by 7ce8d07e92ce953acb49403e6ddb5289f14df7a5

**Comment by heathd** [comment]
@antlerboy-benjamintaylor has informed me that it works
