### ISSUE TITLE
Typo on the idea review screen

### ISSUE THREAD

**Issue by nadinedoyle** [heathd/twentyfiveten#12]
After you input your idea, you are directed to a page to review your idea and amend if needed. Screen says "Your said," and should say "You said." Is there a way to fix this quickly? See attached.
![25 10 capture 1 (004)](https://user-images.githubusercontent.com/82397013/114419732-b124d680-9b81-11eb-8119-587df336775c.JPG)

**Comment by heathd** [comment]
Fab, thanks that should be fixed by 0996bcb which should be deployed shortly!

**Comment by heathd** [comment]
This should be live now
