### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by nadinedoyle** [heathd/twentyfiveten#13]
We tested the app out with a group of fellow facilitators in preparation for a large virtual LS immersion we are doing next week with a client. Wondering if it's possible to address the following issues?:

1. Is there a way to be able to modify the titles of the criteria (i.e. Like AND can support, etc.)
2. What is the minimum number of people who can use the app at a time? 6? Or could you do 5 or less and rate your own idea?

Thanks!

**Comment by heathd** [comment]
> Is there a way to be able to modify the titles of the criteria (i.e. Like AND can support, etc.)

could you explain a bit more, I'm not clear what you're referring to by "criteria"? 

> What is the minimum number of people who can use the app at a time? 6? Or could you do 5 or less and rate your own idea?

there will always be 5 rounds of voting so if there are fewer than 5 people then people will vote on the same idea more than once, but it will still work

**Comment by nadinedoyle** [comment]
Thank you! By criteria I mean the ratings, 1-5. Some of our participants were confused about the way they are written in the app. Honestly I didn’t take a screen shot of that and can’t remember what they are right now – is 1 “like the idea but couldn’t support it” and 5 “love the idea and can support it,” or something like that?

 


NADINE DOYLE


INIFAC® Certified Master Facilitator 

INIFAC® Certified Virtual Facilitator

IAF® Certified Professional Facilitator


(678) 644-6281


***@***.***





 <http://www.doylestrategies.com/> www.doylestrategies.com

**Comment by heathd** [comment]
Ah I see, so like a customisable rating scale.. got it... I've written that idea up as #14

**Comment by heathd** [comment]
closing this now as I think all these points have been dealt with (or recored in a separate issue)
