### ISSUE TITLE
Ability to change the invitation/text

### ISSUE THREAD

**Issue by pixlz** [heathd/twentyfiveten#3]
As an organiser of an event It would be good to be able to change the text (or have another version) for the unconference pitching use case. Instead of “<h3>What is your bold idea to address this challenge?<br/>What if you were ten times bolder?</h3>” to something like "What would you like to discuss with a group at GovCamp North?"

**Comment by heathd** [comment]
Ok here's my solution:

![Screenshot 2020-08-07 at 07-08  14 33 03](https://user-images.githubusercontent.com/61065/89650847-f38f6880-d8ba-11ea-8092-72ec14c311af.png)

I've made the wording a bit more generic and allowed separate explicit prompts for the main prompt and optionally for the first step.

You can also optionally give context.

I think this should give more flexibility.. let me know your thoughts

**Comment by heathd** [comment]
Closing as I think this is resolved now
